// Code generated by mockery v2.52.1. DO NOT EDIT.

package mocks

import (
	tag_alter "github.com/nebula-contrib/nebula-sirius/statement/tag_alter"
	mock "github.com/stretchr/testify/mock"
)

// AlterTagStatementOption is an autogenerated mock type for the AlterTagStatementOption type
type AlterTagStatementOption struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *AlterTagStatementOption) Execute(_a0 *tag_alter.AlterTagStatement) {
	_m.Called(_a0)
}

// NewAlterTagStatementOption creates a new instance of AlterTagStatementOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAlterTagStatementOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *AlterTagStatementOption {
	mock := &AlterTagStatementOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
