// Code generated by mockery v2.52.1. DO NOT EDIT.

package mocks

import (
	edge_alter "github.com/nebula-contrib/nebula-sirius/statement/edge_alter"
	mock "github.com/stretchr/testify/mock"
)

// AlterEdgeStatementOption is an autogenerated mock type for the AlterEdgeStatementOption type
type AlterEdgeStatementOption struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *AlterEdgeStatementOption) Execute(_a0 *edge_alter.AlterEdgeStatement) {
	_m.Called(_a0)
}

// NewAlterEdgeStatementOption creates a new instance of AlterEdgeStatementOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAlterEdgeStatementOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *AlterEdgeStatementOption {
	mock := &AlterEdgeStatementOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
