// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	tag_alter "github.com/nebula-contrib/nebula-sirius/statement/tag_alter"
	mock "github.com/stretchr/testify/mock"
)

// AlterAddDefinitionOption is an autogenerated mock type for the AlterAddDefinitionOption type
type AlterAddDefinitionOption struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *AlterAddDefinitionOption) Execute(_a0 *tag_alter.AlterTypeAddDefinition) {
	_m.Called(_a0)
}

// NewAlterAddDefinitionOption creates a new instance of AlterAddDefinitionOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAlterAddDefinitionOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *AlterAddDefinitionOption {
	mock := &AlterAddDefinitionOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
