// Code generated by mockery v2.52.1. DO NOT EDIT.

package mocks

import (
	edge_alter "github.com/nebula-contrib/nebula-sirius/statement/edge_alter"
	mock "github.com/stretchr/testify/mock"
)

// AlterChangeDefinitionOption is an autogenerated mock type for the AlterChangeDefinitionOption type
type AlterChangeDefinitionOption struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *AlterChangeDefinitionOption) Execute(_a0 *edge_alter.AlterTypeChangeDefinition) {
	_m.Called(_a0)
}

// NewAlterChangeDefinitionOption creates a new instance of AlterChangeDefinitionOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAlterChangeDefinitionOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *AlterChangeDefinitionOption {
	mock := &AlterChangeDefinitionOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
