// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	edge_create "github.com/nebula-contrib/nebula-sirius/statement/edge_create"
	mock "github.com/stretchr/testify/mock"
)

// CreateEdgeStatementOption is an autogenerated mock type for the CreateEdgeStatementOption type
type CreateEdgeStatementOption struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *CreateEdgeStatementOption) Execute(_a0 *edge_create.CreateEdgeStatement) {
	_m.Called(_a0)
}

// NewCreateEdgeStatementOption creates a new instance of CreateEdgeStatementOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCreateEdgeStatementOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *CreateEdgeStatementOption {
	mock := &CreateEdgeStatementOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
