// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	tag_create "github.com/nebula-contrib/nebula-sirius/statement/tag_create"
	mock "github.com/stretchr/testify/mock"
)

// CreateTagStatementOption is an autogenerated mock type for the CreateTagStatementOption type
type CreateTagStatementOption struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *CreateTagStatementOption) Execute(_a0 *tag_create.CreateTagStatement) {
	_m.Called(_a0)
}

// NewCreateTagStatementOption creates a new instance of CreateTagStatementOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCreateTagStatementOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *CreateTagStatementOption {
	mock := &CreateTagStatementOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
