// Code generated by mockery v2.52.1. DO NOT EDIT.

package mocks

import (
	statement "github.com/nebula-contrib/nebula-sirius/statement"
	tag_delete "github.com/nebula-contrib/nebula-sirius/statement/tag_delete"
	mock "github.com/stretchr/testify/mock"
)

// DeleteTagStatementOption is an autogenerated mock type for the DeleteTagStatementOption type
type DeleteTagStatementOption[TVidType statement.VidType] struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *DeleteTagStatementOption[TVidType]) Execute(_a0 *tag_delete.DeleteTagStatement[TVidType]) {
	_m.Called(_a0)
}

// NewDeleteTagStatementOption creates a new instance of DeleteTagStatementOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDeleteTagStatementOption[TVidType statement.VidType](t interface {
	mock.TestingT
	Cleanup(func())
}) *DeleteTagStatementOption[TVidType] {
	mock := &DeleteTagStatementOption[TVidType]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
