// Code generated by mockery v2.52.1. DO NOT EDIT.

package mocks

import (
	edge_delete "github.com/nebula-contrib/nebula-sirius/statement/edge_delete"
	mock "github.com/stretchr/testify/mock"

	statement "github.com/nebula-contrib/nebula-sirius/statement"
)

// DeleteEdgeStatementOption is an autogenerated mock type for the DeleteEdgeStatementOption type
type DeleteEdgeStatementOption[TVidType statement.VidType] struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *DeleteEdgeStatementOption[TVidType]) Execute(_a0 *edge_delete.DeleteEdgeStatement[TVidType]) {
	_m.Called(_a0)
}

// NewDeleteEdgeStatementOption creates a new instance of DeleteEdgeStatementOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDeleteEdgeStatementOption[TVidType statement.VidType](t interface {
	mock.TestingT
	Cleanup(func())
}) *DeleteEdgeStatementOption[TVidType] {
	mock := &DeleteEdgeStatementOption[TVidType]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
