// Code generated by mockery v2.52.1. DO NOT EDIT.

package mocks

import (
	tag_drop "github.com/nebula-contrib/nebula-sirius/statement/tag_drop"
	mock "github.com/stretchr/testify/mock"
)

// DropTagStatementOption is an autogenerated mock type for the DropTagStatementOption type
type DropTagStatementOption struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *DropTagStatementOption) Execute(_a0 *tag_drop.DropTagStatement) {
	_m.Called(_a0)
}

// NewDropTagStatementOption creates a new instance of DropTagStatementOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDropTagStatementOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *DropTagStatementOption {
	mock := &DropTagStatementOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
