// Code generated by mockery v2.52.1. DO NOT EDIT.

package mocks

import (
	edge_drop "github.com/nebula-contrib/nebula-sirius/statement/edge_drop"
	mock "github.com/stretchr/testify/mock"
)

// DropEdgeStatementOption is an autogenerated mock type for the DropEdgeStatementOption type
type DropEdgeStatementOption struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *DropEdgeStatementOption) Execute(_a0 *edge_drop.DropEdgeStatement) {
	_m.Called(_a0)
}

// NewDropEdgeStatementOption creates a new instance of DropEdgeStatementOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDropEdgeStatementOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *DropEdgeStatementOption {
	mock := &DropEdgeStatementOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
