// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	tag_alter "github.com/nebula-contrib/nebula-sirius/statement/tag_alter"
	mock "github.com/stretchr/testify/mock"
)

// IAlterTagTypeDefinition is an autogenerated mock type for the IAlterTagTypeDefinition type
type IAlterTagTypeDefinition struct {
	mock.Mock
}

// GenerateStatement provides a mock function with no fields
func (_m *IAlterTagTypeDefinition) GenerateStatement() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GenerateStatement")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAlterType provides a mock function with no fields
func (_m *IAlterTagTypeDefinition) GetAlterType() tag_alter.AlterType {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAlterType")
	}

	var r0 tag_alter.AlterType
	if rf, ok := ret.Get(0).(func() tag_alter.AlterType); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(tag_alter.AlterType)
	}

	return r0
}

// NewIAlterTagTypeDefinition creates a new instance of IAlterTagTypeDefinition. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIAlterTagTypeDefinition(t interface {
	mock.TestingT
	Cleanup(func())
}) *IAlterTagTypeDefinition {
	mock := &IAlterTagTypeDefinition{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
