// Code generated by mockery v2.52.1. DO NOT EDIT.

package mocks

import (
	edge_alter "github.com/nebula-contrib/nebula-sirius/statement/edge_alter"
	mock "github.com/stretchr/testify/mock"
)

// IAlterEdgeTypeDefinition is an autogenerated mock type for the IAlterEdgeTypeDefinition type
type IAlterEdgeTypeDefinition struct {
	mock.Mock
}

// GenerateStatement provides a mock function with no fields
func (_m *IAlterEdgeTypeDefinition) GenerateStatement() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GenerateStatement")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAlterType provides a mock function with no fields
func (_m *IAlterEdgeTypeDefinition) GetAlterType() edge_alter.AlterType {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAlterType")
	}

	var r0 edge_alter.AlterType
	if rf, ok := ret.Get(0).(func() edge_alter.AlterType); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(edge_alter.AlterType)
	}

	return r0
}

// NewIAlterEdgeTypeDefinition creates a new instance of IAlterEdgeTypeDefinition. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIAlterEdgeTypeDefinition(t interface {
	mock.TestingT
	Cleanup(func())
}) *IAlterEdgeTypeDefinition {
	mock := &IAlterEdgeTypeDefinition{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
