// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	statement "github.com/nebula-contrib/nebula-sirius/statement"
	mock "github.com/stretchr/testify/mock"
)

// IEdgeStatementOperation is an autogenerated mock type for the IEdgeStatementOperation type
type IEdgeStatementOperation[T statement.VidType] struct {
	mock.Mock
}

// GenerateStatement provides a mock function with no fields
func (_m *IEdgeStatementOperation[T]) GenerateStatement() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GenerateStatement")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDstVid provides a mock function with no fields
func (_m *IEdgeStatementOperation[T]) GetDstVid() T {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDstVid")
	}

	var r0 T
	if rf, ok := ret.Get(0).(func() T); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(T)
		}
	}

	return r0
}

// GetOperationType provides a mock function with no fields
func (_m *IEdgeStatementOperation[T]) GetOperationType() statement.OperationTypeStatement {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetOperationType")
	}

	var r0 statement.OperationTypeStatement
	if rf, ok := ret.Get(0).(func() statement.OperationTypeStatement); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(statement.OperationTypeStatement)
	}

	return r0
}

// GetSrcVid provides a mock function with no fields
func (_m *IEdgeStatementOperation[T]) GetSrcVid() T {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSrcVid")
	}

	var r0 T
	if rf, ok := ret.Get(0).(func() T); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(T)
		}
	}

	return r0
}

// NewIEdgeStatementOperation creates a new instance of IEdgeStatementOperation. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIEdgeStatementOperation[T statement.VidType](t interface {
	mock.TestingT
	Cleanup(func())
}) *IEdgeStatementOperation[T] {
	mock := &IEdgeStatementOperation[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
