// Code generated by mockery v2.52.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IInsertableVertex is an autogenerated mock type for the IInsertableVertex type
type IInsertableVertex struct {
	mock.Mock
}

// GetTagName provides a mock function with no fields
func (_m *IInsertableVertex) GetTagName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTagName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// InsertIfNotExists provides a mock function with no fields
func (_m *IInsertableVertex) InsertIfNotExists() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for InsertIfNotExists")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// NewIInsertableVertex creates a new instance of IInsertableVertex. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIInsertableVertex(t interface {
	mock.TestingT
	Cleanup(func())
}) *IInsertableVertex {
	mock := &IInsertableVertex{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
