// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	edge_insert "github.com/nebula-contrib/nebula-sirius/statement/edge_insert"
	mock "github.com/stretchr/testify/mock"

	statement "github.com/nebula-contrib/nebula-sirius/statement"
)

// InsertEdgeStatementOption is an autogenerated mock type for the InsertEdgeStatementOption type
type InsertEdgeStatementOption[TVidType statement.VidType] struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *InsertEdgeStatementOption[TVidType]) Execute(_a0 *edge_insert.InsertEdgeStatement[TVidType]) {
	_m.Called(_a0)
}

// NewInsertEdgeStatementOption creates a new instance of InsertEdgeStatementOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInsertEdgeStatementOption[TVidType statement.VidType](t interface {
	mock.TestingT
	Cleanup(func())
}) *InsertEdgeStatementOption[TVidType] {
	mock := &InsertEdgeStatementOption[TVidType]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
