// Code generated by mockery v2.52.1. DO NOT EDIT.

package mocks

import (
	edge_upsert "github.com/nebula-contrib/nebula-sirius/statement/edge_upsert"
	mock "github.com/stretchr/testify/mock"

	statement "github.com/nebula-contrib/nebula-sirius/statement"
)

// UpsertEdgeStatementOption is an autogenerated mock type for the UpsertEdgeStatementOption type
type UpsertEdgeStatementOption[TVidType statement.VidType] struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *UpsertEdgeStatementOption[TVidType]) Execute(_a0 *edge_upsert.UpsertEdgeStatement[TVidType]) {
	_m.Called(_a0)
}

// NewUpsertEdgeStatementOption creates a new instance of UpsertEdgeStatementOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUpsertEdgeStatementOption[TVidType statement.VidType](t interface {
	mock.TestingT
	Cleanup(func())
}) *UpsertEdgeStatementOption[TVidType] {
	mock := &UpsertEdgeStatementOption[TVidType]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
