// Code generated by mockery v2.52.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// VidType is an autogenerated mock type for the VidType type
type VidType struct {
	mock.Mock
}

// NewVidType creates a new instance of VidType. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVidType(t interface {
	mock.TestingT
	Cleanup(func())
}) *VidType {
	mock := &VidType{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
